[project]
name = "health"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "fpdf==1.7.2",
    "openai>=1.93.0",
    "pydantic>=2.11.7",
    "python-dotenv>=1.0.0",
    "streamlit>=1.46.1",
]

